---
framework: jasmine
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.0
